import Head from "next/head";
import {Title, Text, Container, Button, Stack} from "@mantine/core";
import Header from "@/shared/components/Header";

export default function Home() {
    return (
        <>
            <Head>
                <title>Tone App</title>
                <meta name="description" content="Generated by Zencoder"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Header/>

            <Container size="md" py="xl" style={{marginTop: "100px"}}>
                <Stack align="center" gap="xl">
                    <Title order={1}>Добро пожаловать в Tone App</Title>
                    <Text size="lg">
                        Это базовый проект на Next.js с поддержкой темной и светлой тем.
                    </Text>
                    <Button size="xl" radius="md">
                        Начать работу
                    </Button>

                    {/* Контент для скролла */}
                    {Array.from({length: 10}).map((_, i) => (
                        <div key={i} style={{
                            height: "200px",
                            width: "100%",
                            border: "1px solid rgba(128, 128, 128, 0.1)",
                            borderRadius: "16px",
                            display: "flex",
                            alignItems: "center",
                            justifyContent: "center",
                        }}>
                            Блок контента {i + 1}
                        </div>
                    ))}
                </Stack>
            </Container>
        </>
    );
}
